# SdfQuery.srv

geometry_msgs/Vector3[] query_points
---
uint8                   dim
bool                    success
bool                    compute_gradient
bool                    compute_gradient_variance
bool                    compute_covariance
float64[]               signed_distances
geometry_msgs/Vector3[] gradients
float64[]               variances
float64[]               covariances
